#pragma once
#ifndef WILDCAT_DEBUG_RETCODE_HPP
#define WILDCAT_DEBUG_RETCODE_HPP

/*
	#include <Debug/RetCode.hpp>

	WILDCAT UNIVERSAL RETURN AND ASSIGNMENT VALUES:

		WILDCAT_NULL - VALUE NOT SPECIFIED. USEFUL IF YOU WANT A DEFAULT VALUE FOR A VARIABLE.
		WILDCAT_ERROR
		WILDCAT_SUCCESS
		WILDCAT_NOT_IMPLEMENTED - PLACEHOLDER.
*/

const char WILDCAT_NULL = -1;

	// RETURN IF SOMETHING FUCKED UP.
const char WILDCAT_FAIL = -2;
const char WILDCAT_ERROR = -2;

	// RETURN IF FUNCTION DID NOT GET EXPECTED INPUT, BUT TRIED TO RECOVER.
const char WILDCAT_WARNING = -5;

	// RETURN IF EVERYTHING WORKED.
const char WILDCAT_SUCCESS = -3;
const char WILDCAT_NOT_IMPLEMENTED = -4;

#endif