/*
	WILDCAT UNIVERSAL RETURN AND ASSIGNMENT VALUES;

		// IF YOU DON'T WISH TO SPECIFY THE VALUE OF SOMETHING.
	const char WILDCAT_NULL = -1;
	const char WILDCAT_ERROR = -2;
	const char WILDCAT_SUCCESS = -3;
	const char WILDCAT_NOT_IMPLEMENTED = -4;

*/

